### PR TITLE
Model view change with worflow

### PR DESCRIPTION
**Pull request by XdoctorwhoZ**
The same pr that @Darcraytore1 propose but now I can test while I'm in daddy duty.

### CODE REVIEW

**Comment by XdoctorwhoZ** [comment]
I will let @wardru perform the merge when ok with this

**Comment by wardru** [comment]
I have a bunch of issues.

First when I click on `Self-Managed Broker` for the first time the page is greyed out. I need to go back and try again to get the two buttons available (`Manual Broker` and `Local discovery`).

Log message for this error:
```
flutter: RangeError (length): Invalid value: Not in inclusive range 0..2: 3
flutter: #0      getConnectionsButtonsList.<anonymous closure> (package:panduza_sandbox_flutter/utils_widgets/utils_widgets.dart)
flutter: #1      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1422)
flutter: #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
flutter: #3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:829)
flutter: #4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844)
flutter: #6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
flutter: #7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
flutter: #8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2686)
flutter: #9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097)
flutter: #10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2686)
flutter: #11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
flutter: #12     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:424)
flutter: #13     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:77)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #15     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
flutter: #16     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #18     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
flutter: #19     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1555)
flutter: #20     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1464)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #22     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #25     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #28     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #31     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #34     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #37     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #40     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #43     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #45     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569)
flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #50     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:2575)
flutter: #62     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
flutter: #63     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
flutter: #64     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1063)
flutter: #65     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
flutter: #66     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
flutter: #67     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2414)
flutter: #68     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051)
flutter: #69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064)
flutter: #70     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:582)
flutter: #71     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991)
flutter: #72     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
flutter: #73     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
flutter: #74     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
flutter: #75     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
flutter: #76     _invoke (dart:ui/hooks.dart:312)
flutter: #77     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
flutter: #78     _drawFrame (dart:ui/hooks.dart:283)
```

Having a ton of error messages when I click on `local discovery` even though I have brokers running locally.
They don't appear.

```

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = fd4c:4b32:3232:0:1ac0:4dff:fe66:61e, port = 63500
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582)
#2      platformDiscovery (package:panduza_sandbox_flutter/data/utils.dart:194)
<asynchronous suspension>
#3      _DiscoveryPageState.build.<anonymous closure>.<anonymous closure> (package:panduza_sandbox_flutter/after_setup_pages/discovery_page.dart:122)
<asynchronous suspension>
```

`Manual Connection` works great but there are some bugs/remarks that we should take care of:

1. The form mentions a `Platform name`, it should be a `Connection name`. You can have many platforms behind this connection. Here you connect to a broker, so what you are creating is a connection to a broker.

2. You shouldn't be able to creat a connection if any of the fields is empty.

3. We should check that another connection with the same name doesn't exist already.

4. We should check that another connection with a different name doesn't already have the same IP and port.

5. We should check that the port is a number (it gives an error right now ```flutter: FormatException: Invalid radix-10 number (at character 1)
wfwefwf```)



After that is fixed I'm good to merge!

**Comment by XdoctorwhoZ** [comment]
To track all the issues, we will merge this PR and create issue that will have to be fixed unitary

Self-Managed Broker fails the first time #8

**Comment by XdoctorwhoZ** [comment]
@wardru I let you merge sandbox PR
@Darcraytore1 stop working on this branch, we will merge this one. Then you will have to create smaller PR 🤣

**Pull request merged**
